language: python
addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
python:
  - "3.7.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - sqlite
  - python manage.py test website --keepdb
