sudo: required
dist: xenial
branches:
  only:
    - dev
language: python
python:
  - "3.7.6"

cache:
  apt: true
  pip: true
  directories:
    - $HOME/download-cache
    
addons:
  apt:
    packages:
      - sqlite3
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python manage.py test website --keepdb
