# Generated by Django 2.1.2 on 2020-04-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.PositiveSmallIntegerField(choices=[(1, 'content_writer'), (2, 'content_manager'), (3, 'supervisor'), (4, 'admin')], default=4),
        ),
    ]
